---
name: 'Luarocks tag release'
description: 'Publish a package to Luarocks when a new tag is pushed'
author: 'Marc Jakobi'
branding:
  color: 'purple'
  icon: 'moon'
inputs:
  name:
    description: "The name of the your package"
    required: true
    default: ${{ github.event.repository.name }}
  dependencies:
    description: "List of Luarocks dependencies."
    required: true
    default: ""
  labels:
    description: "List of package labels."
    required: true
    default: ""
  copy_directories:
    description: "List of additional directories to copy."
    required: true
    default: ""
  summary:
    description: "Short description of the package."
    required: true
    default: ""
  detailed_description:
    summary: "Detailed description of the package."
    required: true
    default: ""
  build_type:
    summary: "'builtin' or 'make'"
    required: true
    default: "builtin"
  template:
    summary: "Path to a rockspec template."
    required: true
    default: "/rockspec.template"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
    - ${{ inputs.dependencies }}
    - ${{ inputs.labels }}
    - ${{ inputs.copy-directories }}
    - ${{ inputs.summary }}
    - ${{ inputs.detailed_description }}
    - ${{ inputs.build_type }}
    - ${{ inputs.template }}
