---
name: 'LuaRocks tag release'
description: 'Publish a package to LuaRocks when a new tag is pushed'
author: 'Marc Jakobi'
branding:
  color: 'purple'
  icon: 'moon'
inputs:
  name:
    description: "The name of the your package"
    required: true
    default: ${{ github.event.repository.name }}
  version:
    description: "The version of your package. By default, the git tag is used."
    required: true
    default: ${{ github.ref_name }}
  dependencies:
    description: "List of LuaRocks dependencies."
    required: true
    default: ""
  labels:
    description: "List of package labels."
    required: true
    default: ""
  copy_directories:
    description: "List of additional directories to copy."
    required: true
    default: ""
  summary:
    description: "Short description of the package."
    required: true
    default: ""
  detailed_description:
    description: "Detailed description of the package."
    required: true
    default: ""
  build_type:
    description: "The build type."
    required: true
    default: builtin
    type: choice
    options:
      - builtin
      - make
  template:
    description: "Path to a rockspec template."
    required: true
    default: "/rockspec.template"
  license:
    description: |
      The license SPDX identifier.
      By default, it will be fetched from GitHub.
      But sometimes, GitHub does not recognise it,
      in which case LuaRocks will fall back to this one.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
    - ${{ inputs.version }}
    - ${{ inputs.dependencies }}
    - ${{ inputs.labels }}
    - ${{ inputs.copy-directories }}
    - ${{ inputs.summary }}
    - ${{ inputs.detailed_description }}
    - ${{ inputs.build_type }}
    - ${{ inputs.template }}
    - ${{ inputs.license }}
