---
name: 'LuaRocks tag release'
description: 'Publish a package to LuaRocks when a new tag is pushed'
author: 'Marc Jakobi'
branding:
  color: 'purple'
  icon: 'moon'
inputs:
  name:
    description: "The name of the your package"
    required: true
    default: ${{ github.event.repository.name }}
  version:
    description: "The version of your package. By default, the git tag is used."
    required: true
    default: ${{ github.ref_name }}
  dependencies:
    description: "List of LuaRocks dependencies."
    required: false
  labels:
    description: "List of package labels."
    required: false
  copy_directories:
    description: |
      List of additional directories to copy.
      Only directories that exist will be copied.
      The defaults are taken from Neovim's `:help runtimepath`
      WARNING: Do not add the directories `lua`, `lib` or `rock_manifest`.
    required: true
    default: |
      {{ neovim.plugin.dirs }}
  summary:
    description: "Short description of the package."
    required: false
  detailed_description:
    description: "Detailed description of the package."
    required: false
  template:
    description: "Path to a rockspec template."
    required: false
  license:
    description: |
      The license SPDX identifier.
      By default, it will be fetched from GitHub.
      But sometimes, GitHub does not recognise it,
      in which case LuaRocks will fall back to this one.
    required: false
  test_interpreters:
    description: |
      Lua interpreters to run `luarocks test` with.
      If not set, no tests will be run.
      At the moment, "lua", "neovim-stable" and "neovim-nightly" are supported.
    required: false
    default: |
      neovim-stable
      neovim-nightly
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v22
    - run: |
        nix profile install --accept-flake-config "${{ github.action_path }}#luarocks-tag-release-action"
      shell: bash

    - run: luarocks-tag-release-action
      env:
        INPUT_NAME: ${{ inputs.name }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_DEPENDENCIES: ${{ inputs.dependencies }}
        INPUT_LABELS: ${{ inputs.labels }}
        INPUT_COPY_DIRECTORIES: ${{ inputs.copy_directories }}
        INPUT_SUMMARY: ${{ inputs.summary }}
        INPUT_DETAILED_DESCRIPTION: ${{ inputs.detailed_description }}
        INPUT_TEMPLATE: ${{ inputs.template }}
        INPUT_LICENSE: ${{ inputs.license }}
        INPUT_TEST_INTERPRETERS: ${{ inputs.test_interpreters }}
      shell: bash
