---
name: Conventional Commits

on:
  pull_request:
    branches: [master]

jobs:
  check-conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        with:
          config-preset: angular
