---
name: "Tests and checks"
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      - name: Nix checks
        run: nix flake check -L
  build:
    name: ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#luarocks-tag-release-action
          - .#devShells.x86_64-linux.default
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
    - uses: cachix/cachix-action@v12
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --accept-flake-config "${{matrix.attribute}}" -L
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Luarocks install
        uses: ./
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          dependencies: |
            dkjson
          version: "0.0.0"
          upload: false
          copy_directories: |
            {{ neovim.plugin.dirs }}
            bin
