---
name: "Tests and checks"
on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      - name: Nix checks
        run: nix flake check -L
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Luarocks install
        uses: ./
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          dependencies: |
            dkjson
          version: "0.0.0"
          upload: false
          copy_directories: |
            {{ neovim.plugin.dirs }}
            bin
