---
name: "Test Luarocks install"
on: pull_request

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Test Luarocks install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Luarocks install
        uses: ./
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          dependencies: |
            plenary.nvim
          version: "0.0.0"
          upload: false
          copy_directories: |
            {{ neovim.plugin.dirs }}
            bin
