---
permissions:
  contents: write
  pull-requests: write

name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release-please
      uses: google-github-actions/release-please-action@v3
      with:
        token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        release-type: simple
        package-name: luarocks-tag-release
        command: release-pr
        signoff: "Marc Jakobi<marc@jakobi.dev>"
    - uses: reitermarkus/automerge@v2
      with:
        token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        merge-method: squash
        pull-request: ${{ github.event.inputs.pull-request }}
