---
permissions:
  contents: write
  pull-requests: write

name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release-please
      uses: google-github-actions/release-please-action@v3
      with:
        token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        release-type: simple
        package-name: luarocks-tag-release
        command: release-pr
        signoff: "Marc Jakobi<marc@jakobi.dev>"
    # - name: Release
    #   uses: actions/create-release@v1
    #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
    #   with:
    #     tag_name: ${{ steps.changelog.outputs.tag }}
    #     release_name: ${{ steps.changelog.outputs.tag }}
    #     body: ${{ steps.changelog.outputs.clean_changelog }}
