---
name: "Luarocks release"
on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luarocks Upload
        uses: ./
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          dependencies: |
            dkjson
          labels: |
            neovim
          summary: "Luarocks release workflow for GitHub"
          detailed_description: |
            This is not a real lua package.
            It exists for the purpose of testing the workflow.
          copy_directories: |
            {{ neovim.plugin.dirs }}
            bin
